<?php
/**
 * @file
 * Code for the BF LinkedIn feature.
 */

include_once 'bf_linkedin.features.inc';

/**
 * Implements hook_linkedin_user_save().
 *
 * When a user account is created from LinkedIn, add role and profile fields.
 */
function bf_linkedin_linkedin_user_save($account, $liuser) {
  $edit = array();

  // Add Fin Advisor role.
  $fa_role = user_role_load_by_name('Financial Advisor');
  $edit['roles'] = $account->roles + array($fa_role->rid => $fa_role->name);

  // Enable display of user LinkedIn data.
  $edit['data']['linkedin_profile_user_page_enabled'] = 1;

  // Use name from LinkedIn.
  $edit['name'] = $liuser['person']['first-name'] . ' ' . $liuser['person']['last-name'];

  // Set user account picture if available.
  $pic = linkedin_get_profile_fields($account->uid, array('picture-url'));
  if (isset($pic['picture-url'])) {
    $file = system_retrieve_file($pic['picture-url'], 'public://pictures', TRUE, FILE_EXISTS_REPLACE);
    $edit['picture'] = $file;
  }

  // Save user account settings.
  user_save($account, $edit);
}
