<?php
/**
 * @file
 * bf_aging_wellness_disease.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function bf_aging_wellness_disease_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'Autism Research',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '0155050e-ec44-4487-b395-e8a213e74d4b',
    'vocabulary_machine_name' => 'aging_wellness_disease',
  );
  $terms[] = array(
    'name' => 'Optical, Vision Research',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '03332d11-dda2-4713-b172-493e6f44deeb',
    'vocabulary_machine_name' => 'aging_wellness_disease',
  );
  $terms[] = array(
    'name' => 'Kidneys, Urology Research',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '0817da29-e191-409a-a449-a7cce5085e57',
    'vocabulary_machine_name' => 'aging_wellness_disease',
  );
  $terms[] = array(
    'name' => 'Muscular Dystrophy Research',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '118d39a9-d6f2-49d1-ba01-eef87cd7c829',
    'vocabulary_machine_name' => 'aging_wellness_disease',
  );
  $terms[] = array(
    'name' => 'Multiple Sclerosis Research',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '174993ae-dbf9-4286-903c-efd63089f003',
    'vocabulary_machine_name' => 'aging_wellness_disease',
  );
  $terms[] = array(
    'name' => 'Breast Cancer Research',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '1f64c8e4-b093-4659-9076-975ecfbeaaab',
    'vocabulary_machine_name' => 'aging_wellness_disease',
  );
  $terms[] = array(
    'name' => 'ALS, Lou Gherig\'s Disease Research',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '22640ae8-b960-468b-a779-297d2ec563e1',
    'vocabulary_machine_name' => 'aging_wellness_disease',
  );
  $terms[] = array(
    'name' => 'HIV AIDS Research',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '30d90bbd-b2a7-4694-a70f-49a9aab70262',
    'vocabulary_machine_name' => 'aging_wellness_disease',
  );
  $terms[] = array(
    'name' => 'Pulmonary, Respiratory Research',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '3bf9ceb2-c074-4503-a166-29727149af39',
    'vocabulary_machine_name' => 'aging_wellness_disease',
  );
  $terms[] = array(
    'name' => 'Cancer Research',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '3d82ecc4-a91c-4e59-adb1-d8add9a434fe',
    'vocabulary_machine_name' => 'aging_wellness_disease',
  );
  $terms[] = array(
    'name' => 'Pregnancy, Reproduction Research',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '58ee502d-2d48-4e8b-ba2c-6eb294975b13',
    'vocabulary_machine_name' => 'aging_wellness_disease',
  );
  $terms[] = array(
    'name' => 'Alcoholism, Addiction, Substance Abuse Research',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '5cb080ad-17ca-42c7-989b-7ccc079afa85',
    'vocabulary_machine_name' => 'aging_wellness_disease',
  );
  $terms[] = array(
    'name' => 'Microbiome, Digestive Track Research',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '5db74016-8a46-40d9-ad42-2276e8463306',
    'vocabulary_machine_name' => 'aging_wellness_disease',
  );
  $terms[] = array(
    'name' => 'Pancreas Research',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '64618700-1402-4a93-9234-8fadbbc5a9ae',
    'vocabulary_machine_name' => 'aging_wellness_disease',
  );
  $terms[] = array(
    'name' => 'Tourette\'s Syndrome Research',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '73fc55fb-2571-4cfd-9764-eae74e7e0eef',
    'vocabulary_machine_name' => 'aging_wellness_disease',
  );
  $terms[] = array(
    'name' => 'Mental Health, Depression Research',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '7add064b-089e-4b92-86b5-277b40de108b',
    'vocabulary_machine_name' => 'aging_wellness_disease',
  );
  $terms[] = array(
    'name' => 'Pain Management Research',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '7c6146ef-4316-4cf9-a65f-81941be5cfef',
    'vocabulary_machine_name' => 'aging_wellness_disease',
  );
  $terms[] = array(
    'name' => 'Pediatric Research',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '89f7f677-5a93-4e58-a55b-35dc8cf92230',
    'vocabulary_machine_name' => 'aging_wellness_disease',
  );
  $terms[] = array(
    'name' => 'Wellness, Aging Research',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '91db2af9-6e20-4c04-a5ed-2d39d27ec9eb',
    'vocabulary_machine_name' => 'aging_wellness_disease',
  );
  $terms[] = array(
    'name' => 'Auditory, Hearing, Sensing Research',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'a11142a4-12df-49e0-a42e-4605d651d48b',
    'vocabulary_machine_name' => 'aging_wellness_disease',
  );
  $terms[] = array(
    'name' => 'Malaria Research',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'a9fe3c00-2522-46a6-93cc-94246009153c',
    'vocabulary_machine_name' => 'aging_wellness_disease',
  );
  $terms[] = array(
    'name' => 'Parkinson\'s Disease Research',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'ae0a7c84-1d86-4c16-be85-c307948f0bf8',
    'vocabulary_machine_name' => 'aging_wellness_disease',
  );
  $terms[] = array(
    'name' => 'Cardiovascular, Heart Disease Research',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'b3413388-7028-4640-a1fb-ff915c3c0dc4',
    'vocabulary_machine_name' => 'aging_wellness_disease',
  );
  $terms[] = array(
    'name' => 'Alzheimer\'s, Dementia Research',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'c28b5b6e-162f-4c6b-97bd-0e790a1c471b',
    'vocabulary_machine_name' => 'aging_wellness_disease',
  );
  $terms[] = array(
    'name' => 'Muscular, Skeletal, Orthopedics Research',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'c942c67b-4b91-41df-a1b1-3b7639898f90',
    'vocabulary_machine_name' => 'aging_wellness_disease',
  );
  $terms[] = array(
    'name' => 'Longevity, Immortality Research',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'd5ef41ad-8e6d-4590-9aa2-e87904e4e1f0',
    'vocabulary_machine_name' => 'aging_wellness_disease',
  );
  $terms[] = array(
    'name' => 'Diabetes Research',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'df062c10-4d41-4ccd-919a-a11e5dfdae8a',
    'vocabulary_machine_name' => 'aging_wellness_disease',
  );
  $terms[] = array(
    'name' => 'Ovarian Cancer Research',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'f5f64788-de8f-46b4-9a19-2b0237b1c76b',
    'vocabulary_machine_name' => 'aging_wellness_disease',
  );
  $terms[] = array(
    'name' => 'Autoimmune Research',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'f63b6b83-2c4b-418e-b3e4-3353b056c942',
    'vocabulary_machine_name' => 'aging_wellness_disease',
  );
  $terms[] = array(
    'name' => 'Dentistry, Oral Hygiene Research',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'f87b1ade-5783-4c4f-a716-9679a013d558',
    'vocabulary_machine_name' => 'aging_wellness_disease',
  );
  return $terms;
}
