<?php

/**
 * Implements hook_form_alter().
 */
function sitemod_form_alter(&$form, &$form_state, $form_id) {
  switch ($form_id) {
    case 'cause_node_form':
      $form['#validate'][] = 'sitemod_cause_node_validate';
      $form['title']['#description'] = t('The First Letter Of Each Word Must Be In Caps. 3-5 word max.');
      break;

    case 'apachesolr_search_custom_page_search_form':
      $form['#attributes']['class'][] = 'col-xs-12 col-sm-10 col-sm-offset-1';
      $form['basic']['submit']['#attributes']['class'][] = 'btn-default';
      $form['basic']['submit']['#value'] = 'Go';
      break;

    case 'client_profile_node_form':
      // Set multi column checkboxes for research areas.
      $form['field_research_areas'][LANGUAGE_NONE]['#multicolumn'] = array('width' => 8);

      // Add add'l markup to cause matches and provide default values.
      $form['field_cause_matches']['#after_build'][] = 'sitemod_client_profile_form_afterbuild';
      foreach (variable_get('benefunder_default_matches', array(117, 72)) as $i => $nid) {
        $node = node_load($nid);
        $form['field_cause_matches'][LANGUAGE_NONE][$i]['target_id'] = array(
          '#type' => 'checkbox',
          '#delta' => $i,
          '#return_value' => $nid,
          '#value' => $nid,
          '#title_display' => 'after',
          '#field_suffix' => sprintf('<label class="option" for="edit-field-cause-matches-und-%d">%s</label>', $i, $node->title),
          '#name' => "field_cause_matches[und][$i][target_id]",
          '#attributes' => array(
            'checked' => 'checked',
            'id' => "edit-field-cause-matches-und-$i",
            'data-delta' => $i,
         ));
      }
      break;
  }
}

function sitemod_client_profile_form_afterbuild($element) {
//  $element['#prefix'] = <<<ENDHTML
//<div id="cause-markup" class="container">
//<div class="row">
//  <div class="col-sm-3">
//    <p>Quick Start<p>
//    <p>Use our pre-selected examples of Causes to print out
//    sample reports to present to clients during your philanthropy discussions.</p>
//    <p><a href="/node/123">Lorem Ipsum dolor sit amet, sit pulvinar incidunt</a></p>
//    <p><a href="/node/123">Lorem Ipsum dolor sit amet, sit pulvinar incidunt</a></p>
//    <p><a href="/node/123">Lorem Ipsum dolor sit amet, sit pulvinar incidunt</a></p>
//    <p><a href="/node/123">Lorem Ipsum dolor sit amet, sit pulvinar incidunt</a></p>
//    <p><a href="/node/123">Lorem Ipsum dolor sit amet, sit pulvinar incidunt</a></p>
//    <p><a href="/node/123">Lorem Ipsum dolor sit amet, sit pulvinar incidunt</a></p>
//    <p><a href="/node/123">Lorem Ipsum dolor sit amet, sit pulvinar incidunt</a></p>
//    <p><a href="/node/123">Lorem Ipsum dolor sit amet, sit pulvinar incidunt</a></p>
//  </div>
//  <div class="col-sm-3">
//    <p>DIY Matching</p>
//    <p>Know your client's interests? Impress them with a customized proposal of
//    exciting research projects that match their giving history</p>
//  </div>
//  <div class="col-sm-3">
//    <p>Supported Matching</p>
//    <p>Work with our knowledgeable team to tailor a proposal for your customer.
//    Fill out the profile information and we'll give you a custom match.</p>
//    <p>
//      <form class="vboutTheme_vbout01_request-a-demo-form" action="" method="post" id="nide68ed891-2d04-d18f-6b21-4583b85d639e">
//      <div class="request-a-demo-form-Div">
//        <h3 class="request-a-demo-Form-Title">GET HELP MATCHING CAUSES<br /></h3>
//      </div>
//      <div class="request-a-demo-form-input">
//        <input type="text" name="vbout_EmbedForm[field][id1479391210534-1]" value="" placeholder="Name*" id="nid47af761e-ac40-340f-9ad2-8c46de8b9349" />
//        <input type="email" name="vbout_EmbedForm[field][id1479391210534-2]" value="" placeholder="Email*" id="nidc3a3cb05-94db-303e-c00d-4a1a8cb66c1a" />
//        <input type="text" name="vbout_EmbedForm[field][id1479391210534-4]" value="" placeholder="Company Name" id="nid1672f791-2a28-7151-1d33-a5e344687922" />
//        <input type="tel" name="vbout_EmbedForm[field][id1479391210534-3]" value="" placeholder="Phone" id="nid84963266-4ff8-14cc-e536-8625897e6653" />
//      </div>
//      <div class="vbfs-buttons">
//        <div class="vbfs-submit">
//          <input type="submit" value="REQUEST SUPPORT" class="vbout_button" id="nidb218e856-7ea6-d758-6370-01ad528bbaa0" name="vbout_EmbedForm[field][id1479391210534-7]" />
//        </div>
//      </div>
//      </form>
//  </p>
//  </div>
//  <div class="col-sm-3">
//    <p>Concierge Service</p>
//    <p>For donations of more than $250k, our Strategist will meet with you and
//    your client to select the right Causes for your client.</p>
//  </div>
//</div>
//</div>
//ENDHTML;
  $element['#prefix'] = 'We have added sample causes for you below.';
  return $element;
}


/**
 * Custom validation for research area field in cause nodes
 *
 * Check if a top level research area has been selected
 */
function sitemod_cause_node_validate($form, &$form_state) {
  $lang = $form['field_research_area']['#language'];
  $top_level_selected = 0;

  // Check if empty
  if ((count($form_state['values']['field_research_area'][$lang]) == 1) && ($form_state['values']['field_research_area'][$lang][0]['tid'] == NULL)) {
    return form_set_error('field_research_area', t('You must select a top-level (parent) research area.  Example: Life or Technology.'));
  }

  // Check if one is top level
  foreach ($form_state['values']['field_research_area'][$lang] as $research_area) {
    $parent = taxonomy_get_parents($research_area['tid']);
    if (empty($parent)) {
      $top_level_selected++;
    }
  }

  if (!$top_level_selected) {
    form_set_error('field_research_area', t('You must select a top-level (parent) research area. Example: Life or Technology.'));
  }
  elseif ($top_level_selected > 1) {
    form_set_error('field_research_area', t('You may only select 1 top-level (parent) research area. Example: Life or Technology.'));
  }
}

/**
 * Changing the text for share links
 */
function sitemod_service_links_alter(&$links) {
  $links['facebook']['name'] = t('Share on Facebook');
  $links['twitter']['name'] = t('Share on Twitter');
  $links['linkedin']['name'] = t('Share on LinkedIn');
}


/**
 * Used in display suite field "Search result - node link"
 */
function sitemod_node_link($entity) {
  if (isset($entity->nid)) {
    $alias = drupal_get_path_alias('node/' . $entity->nid);
    $full_path = url($alias, array('absolute' => true));
    $options = array(
      'attributes' => array(
        'class' => array('search-teaser-link'),
      ),
    );
    return l($full_path, $alias, $options);
  }
}

/**
 * Alter the results of entity_view() for profiles.
 *
 * @param $build
 *   A renderable array representing the profile content.
 *
 * This hook is called after the content has been assembled in a structured
 * array and may be used for doing processing which requires that the complete
 * profile content structure has been built.
 *
 * If the module wishes to act on the rendered HTML of the profile rather than
 * the structured content array, it may use this hook to add a #post_render
 * callback. Alternatively, it could also implement hook_preprocess_profile2().
 * See drupal_render() and theme() documentation respectively for details.
 *
 * @see hook_entity_view_alter()
 */
function sitemod_profile2_view_alter($build) {
  if ($build['#view_mode'] == 'account') {
    $build['#entity']->label = t('Financial Advisor Dashboard');
  }
}

/**
 * Implements hook_preprocess_HOOK().
 *
 * Set up additional variables for printing PDFs.
 */
function sitemod_preprocess_print(&$variables) {
  $format = $variables['format'];
  if ($format == 'pdf') {
    $node_wrapper = entity_metadata_wrapper('node', $variables['node']);
    $academic_positions = array();

    $variables['subtitle'] = $node_wrapper->field_subtitle->value();
    $variables['name'] = $node_wrapper->field_first_name->value() . ' ' . $node_wrapper->field_last_name->value();
    $variables['picture'] = $node_wrapper->field_picture->value();
    $variables['current_research'] = $node_wrapper->body->value->value();
    $variables['summary'] = text_summary($node_wrapper->field_summary->value->value(), 'filtered_html', 475);

    $picture = $node_wrapper->field_picture->value();
    $picture_url = file_create_url($picture['uri']);
    $variables['picture'] = '<img src="' . $picture_url . '"/>';

    foreach ($node_wrapper->field_academic_position as $position) {
      list($post, $school, $when) = explode('<BR>', $position->value->raw());
      if ($when == 'current') {
        $academic_positions[] = $post . ' at ' . $school;
      }
      $variables['academic_positions'] = implode('<br>', $academic_positions);
    }

    $awards = array();
    foreach ($node_wrapper->field_awards as $award) {
      $awards[] = $award->field_award_title->value();
    }
    if (!empty($awards)) {
      $variables['awards'] = implode('<br>', $awards);
    }

  }
}
