<?php

/**
 * Implements hook_block_info().
 */
function request_information_form_block_info() {
  $blocks['request_information_form'] = array(
    'info' => t('Request Information Form'),
    // Cache per page, since this changes based on a page field value.
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function request_information_form_block_view($delta = '') {
  switch ($delta) {
    case 'request_information_form':
      $block['subject'] = t('Request Information');
      $block['content'] = request_information_form_contents($delta);
      break;
  }
  return $block;
}

/**
 * A module-defined block content function.
 */
function request_information_form_contents($which_block) {
  switch ($which_block) {
    case 'request_information_form':
      $arg1 = arg(1);

      if ((arg(0) == 'node') && !empty($arg1)) {
        $wrapper = entity_metadata_wrapper('node', $arg1);
        $bundle = $wrapper->getBundle();
        if ($bundle == 'page') {
          $show_form = $wrapper->field_show_request_information_f->value();
          if ($show_form) {
            global $base_url;
            $vars = array('base_url' => $base_url);
            return theme('request_information_form_template', $vars);
          }
        }
        elseif ($bundle == 'cause') {
          global $base_url;
          $vars = array('base_url' => $base_url);
          return theme('request_information_form_template', $vars);
        }
      }
  }
}

/**
 * Implements hook_theme().
 */
function request_information_form_theme() {
  return array(
    'request_information_form_template' => array(
      'template' => 'request_information_form',
      'path' => drupal_get_path('module', 'request_information_form'),
      'type' => 'theme',
    ),
  );
}