<?php

/**
 * Implements hook_block_info().
 *
 * This hook declares what blocks are provided by the module.
 */
function homepage_featured_causes_block_info() {
  $blocks['homepage_featured_causes'] = array(
    'info' => t('Homepage Featured Causes'),
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 *
 * This hook generates the contents of the blocks themselves.
 */
function homepage_featured_causes_block_view($delta = '') {
  // The $delta parameter tells us which block is being requested.
  switch ($delta) {
    case 'homepage_featured_causes':
      $block['content'] = homepage_featured_causes_contents($delta);
      break;
  }
  return $block;
}

/**
 * A module-defined block content function.
 */
function homepage_featured_causes_contents($which_block) {
  switch ($which_block) {
    case 'homepage_featured_causes':
      $vars = array();

      /* Homepage node */
      $wrapper = entity_metadata_wrapper('node', 12);

      /* Body text */
      $vars['featured_causes_text'] = $wrapper->body->value->value();

      /* Data from causes */
      $causes = array();
      $field_featured_causes = $wrapper->field_featured_causes->value();

      foreach ($field_featured_causes as $key => $featured_cause) {
        if ($featured_cause->status) {
          $cause = entity_metadata_wrapper('node', $featured_cause->nid);

          /* NID */
          $causes[$key]['nid'] = $featured_cause->nid;

          /* Title */
          $causes[$key]['title'] = $cause->title->value();

          /* Research area name */
          $research_areas = $cause->field_research_area->value();

          /* Find top level research area */
          $top_level_research_area = NULL;
          foreach ($research_areas as $research_area) {
            $parent = taxonomy_get_parents($research_area->tid);
            if (empty($parent)) {
              $top_level_research_area = $research_area;
            }
          }
          $causes[$key]['research_area_name'] = $top_level_research_area->name;

          /* Research area icon (white) */
          $causes[$key]['research_area_icon_white'] = file_create_url($top_level_research_area->field_term_icon['und'][0]['uri']);

          /* Research area icon (color) */
          $causes[$key]['research_area_icon_color'] = file_create_url($top_level_research_area->field_term_icon_with_color_['und'][0]['uri']);

          /* Cause image */
          $jumbotron_image = $cause->field_jumbotron_image->value();
          $causes[$key]['image'] = file_create_url($jumbotron_image['uri']);

          /* Researcher image */
          $researcher_image = $cause->field_picture->value();
          $causes[$key]['researcher_image'] = file_create_url($researcher_image['uri']);

          /* Researcher text */
          $causes[$key]['researcher_text'] = $cause->field_overlay_copy->value();

          /* Researcher name */
          $causes[$key]['researcher_name'] = $cause->field_first_name->value() . ' ' . $cause->field_last_name->value();

          /* Overlay copy */
          $causes[$key]['overlay_copy'] = $cause->field_overlay_copy->value();

          /* Research area CSS class */
          $research_area_css_class = '';
          switch ($top_level_research_area->tid) {
            case 10:
              $research_area_css_class = 'environment';
              break;
            case 7:
              $research_area_css_class = 'humanities';
              break;
            case 66:
              $research_area_css_class = 'life';
              break;
            case 91:
              $research_area_css_class = 'technology';
              break;
          }
          $causes[$key]['research_area_css_class'] = $research_area_css_class;
        }
        else {
          /* If unpublished */
          $causes[$key] = NULL;
        }
      }

      $vars['causes'] = $causes;

      /* Send all data to template file and return as block content */
      return theme('homepage_featured_causes_template', $vars);
  }
}

/**
 * Implements hook_theme().
 */
function homepage_featured_causes_theme() {
  return array(
    'homepage_featured_causes_template' => array(
      'template' => 'homepage_featured_causes',
      'path' => drupal_get_path('module', 'homepage_featured_causes'),
      'type' => 'theme',
    ),
  );
}