<?php

/**
 * Implements hook_block_info().
 *
 * This hook declares what blocks are provided by the module.
 */
function homepage_research_areas_block_info() {
  $blocks['homepage_research_areas'] = array(
    'info' => t('Homepage Research Areas'),
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 *
 * This hook generates the contents of the blocks themselves.
 */
function homepage_research_areas_block_view($delta = '') {
  // The $delta parameter tells us which block is being requested.
  switch ($delta) {
    case 'homepage_research_areas':
      $block['content'] = homepage_research_areas_contents($delta);
      break;
  }
  return $block;
}

/**
 * A module-defined block content function.
 */
function homepage_research_areas_contents($which_block) {
  switch ($which_block) {
    case 'homepage_research_areas':
      $vars = array();

      // Load up the main research areas for causes
      $environment = entity_metadata_wrapper('taxonomy_term', 10);
      $humanities = entity_metadata_wrapper('taxonomy_term', 7);
      $life = entity_metadata_wrapper('taxonomy_term', 66);
      $technologies = entity_metadata_wrapper('taxonomy_term', 91);

      // Get icons
      $environment_icon = $environment->field_term_icon_with_color_->value();
      $humanities_icon = $humanities->field_term_icon_with_color_->value();
      $life_icon = $life->field_term_icon_with_color_->value();
      $technologies_icon = $technologies->field_term_icon_with_color_->value();
      $vars['environment_icon'] = file_create_url($environment_icon['uri']);
      $vars['humanities_icon'] = file_create_url($humanities_icon['uri']);
      $vars['life_icon'] = file_create_url($life_icon['uri']);
      $vars['technologies_icon'] = file_create_url($technologies_icon['uri']);

      // Get images
      $environment_image = $environment->field_term_image->value();
      $humanities_image = $humanities->field_term_image->value();
      $life_image = $life->field_term_image->value();
      $technologies_image = $technologies->field_term_image->value();
      $vars['environment_image'] = image_style_url('homepage_-_top_level_categories', $environment_image['uri']);
      $vars['humanities_image'] = image_style_url('homepage_-_top_level_categories', $humanities_image['uri']);
      $vars['life_image'] = image_style_url('homepage_-_top_level_categories', $life_image['uri']);
      $vars['technologies_image'] = image_style_url('homepage_-_top_level_categories', $technologies_image['uri']);

      // Get text
      $vars['environment_text'] = $environment->description->value();
      $vars['humanities_text'] = $humanities->description->value();
      $vars['life_text'] = $life->description->value();
      $vars['technologies_text'] = $technologies->description->value();

      // Send icons and text to template file and return as block content
      return theme('homepage_research_areas_template', $vars);
  }
}

/**
 * Implements hook_theme().
 */
function homepage_research_areas_theme() {
  return array(
    'homepage_research_areas_template' => array(
      'template' => 'homepage_research_areas',
      'path' => drupal_get_path('module', 'homepage_research_areas'),
      'type' => 'theme',
    ),
  );
}