<?php
/**
 * @file
 * bf_taxonomies.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function bf_taxonomies_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'Memorial Sloan Kettering Cancer Center',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '00b8c6ca-5a84-4d81-ad68-3efa545efbc4',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Michigan State University',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '0132e857-60fc-4168-9cda-4df92f69f370',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Infectious',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '020167bc-7d5d-49be-b94d-680abe7e962d',
    'vocabulary_machine_name' => 'research_area',
    'field_term_icon' => array(),
    'field_term_image' => array(),
    'field_term_icon_with_color_' => array(),
    'parent' => array(
      0 => '571713b2-f33e-448f-a4bc-fc967f7dbf1d',
    ),
  );
  $terms[] = array(
    'name' => 'University Of Iowa',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '04085a8a-7991-452a-9a2d-46058282940b',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Colorado State University',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '046bfc1c-0e5b-4b7c-9d8f-6a5f6b639d7d',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Broad Institute',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '070c2894-b985-4775-9eca-a2331c78b299',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Humanities',
    'description' => 'Marfa vinyl literally Helvetica roof party, food truck hella +1 Wes Anderson Blue Bottle. Mumblecore post-ironic crucifix try-hard. Kogi letterpress 3 wolf moon. Marfa vinyl literally Helvetica roof party, food truck hella +1 Wes Anderson Blue Bottle. Mumblecore post-ironic crucifix try-hard. Kogi letterpress 3 wolf moon.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '080b773f-5832-47fb-92d9-6a65271fa81a',
    'vocabulary_machine_name' => 'research_area',
    'field_term_icon' => array(),
    'field_term_image' => array(),
    'field_term_icon_with_color_' => array(),
  );
  $terms[] = array(
    'name' => 'Yale University',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '09484782-e6b8-4867-afe7-6d439e1e3da2',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Portland State University',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '0abbcdb9-5fa2-4f3e-b3dc-398f6400f7f4',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Environment',
    'description' => 'Marfa vinyl literally Helvetica roof party, food truck hella +1 Wes Anderson Blue Bottle. Mumblecore post-ironic crucifix try-hard. Kogi letterpress 3 wolf moon. Helvetica roof party, food truck hella +1 Wes Anderson Blue Bottle.
',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '0b1631a9-faa8-47a2-8de3-834fbc6960d2',
    'vocabulary_machine_name' => 'research_area',
    'field_term_icon' => array(),
    'field_term_image' => array(),
    'field_term_icon_with_color_' => array(),
  );
  $terms[] = array(
    'name' => 'Brigham Young University',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '0b44de7b-84af-48c3-9e65-ee45f169faa9',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Northwestern University',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '0b4e2494-03a5-4417-bb28-216e8fd2f876',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'University Of New Mexico',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '0c85e14f-6f9a-4b22-a89d-2ff4a754e427',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Health IT',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '0d8366ce-a46c-4668-898b-5fbd4231f1c9',
    'vocabulary_machine_name' => 'research_area',
    'field_term_icon' => array(),
    'field_term_image' => array(),
    'field_term_icon_with_color_' => array(),
    'parent' => array(
      0 => '571713b2-f33e-448f-a4bc-fc967f7dbf1d',
    ),
  );
  $terms[] = array(
    'name' => 'Case Western Reserve University',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '0eb132f8-4638-455e-a0dc-e119dbaefaad',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Stony Brook U.',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '0ecb77af-4c8c-45cb-bb3c-e07556ed05d0',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Harvard University (Medical School)',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1088c2c4-7c40-424a-a1ad-e47998fd0972',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Cardiovascular',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1382af75-3617-4c82-a6fb-d8894a72e380',
    'vocabulary_machine_name' => 'research_area',
    'field_term_icon' => array(),
    'field_term_image' => array(),
    'field_term_icon_with_color_' => array(),
    'parent' => array(
      0 => '571713b2-f33e-448f-a4bc-fc967f7dbf1d',
    ),
  );
  $terms[] = array(
    'name' => 'Guttmacher Institute',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '13cd3ba8-6e88-455b-b9ba-6f3ad2880747',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'University Of California Irvine',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1429b95b-7e97-430f-95f9-f6887c14f87f',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Energy',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '14639664-8b2d-4b6f-964c-ec1dd736d7bb',
    'vocabulary_machine_name' => 'research_area',
    'field_term_icon' => array(),
    'field_term_image' => array(),
    'field_term_icon_with_color_' => array(),
    'parent' => array(
      0 => '0b1631a9-faa8-47a2-8de3-834fbc6960d2',
    ),
  );
  $terms[] = array(
    'name' => 'University Of Wisconsin-Madison',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '168a6343-b8b5-46aa-82f3-753e92500520',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'State University New York Stony Brook',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '181d271f-4b8e-4fb4-86d9-411f179c1ca1',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Nanotechnology',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1a5e6ef5-9134-4821-84ea-438a74fb4917',
    'vocabulary_machine_name' => 'research_area',
    'field_term_icon' => array(),
    'field_term_image' => array(),
    'field_term_icon_with_color_' => array(),
    'parent' => array(
      0 => '797fa9c6-81a9-4032-b846-763ed1162542',
    ),
  );
  $terms[] = array(
    'name' => 'University Of Colorado Denver',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1ce765ce-ab79-4d7b-9900-4bc53ba5eea5',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Musculoskeletal',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1e09a259-b5d5-410d-8398-095a5b0a5a14',
    'vocabulary_machine_name' => 'research_area',
    'field_term_icon' => array(),
    'field_term_image' => array(),
    'field_term_icon_with_color_' => array(),
    'parent' => array(
      0 => '571713b2-f33e-448f-a4bc-fc967f7dbf1d',
    ),
  );
  $terms[] = array(
    'name' => 'Tulane University Of Louisiana',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1ea43dff-e1a3-42f2-b7c6-c099fb07d680',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Stevens Institute Of Technology',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '207a6cb7-0194-4719-a9ee-3d591abf703a',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Purdue University West Lafayette',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '209c95a9-1f6c-4389-ba66-4d88712829aa',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'University Of Delaware',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '22ec5610-e336-45f1-a0ac-0d79271cb277',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'West Virginia University',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '24b9e4a9-defe-4841-9a81-e392f45d95e3',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'University Of Illinois Urbana-Champaign',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '24c9cd62-b7c7-4777-8fb8-e3a9e55ba3cf',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Economics',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '2550e357-5492-4833-8c10-b532274f586c',
    'vocabulary_machine_name' => 'research_area',
    'field_term_icon' => array(),
    'field_term_image' => array(),
    'field_term_icon_with_color_' => array(),
    'parent' => array(
      0 => '080b773f-5832-47fb-92d9-6a65271fa81a',
    ),
  );
  $terms[] = array(
    'name' => 'State University Of New York At Albany',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '2581c7da-db44-4a96-9e9a-786c4432314c',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'George Mason University',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '2944950f-df89-47e7-939c-f1669200a6db',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Duke University',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '2a8e3389-add5-4a76-9993-e324d378f640',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Los Alamos National Laboratory',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '2daf2b94-4614-4564-bac6-9b01756934a2',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'History',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '2e7af326-d26e-4b1a-afb3-9a3f25cad630',
    'vocabulary_machine_name' => 'research_area',
    'field_term_icon' => array(),
    'field_term_image' => array(),
    'field_term_icon_with_color_' => array(),
    'parent' => array(
      0 => '080b773f-5832-47fb-92d9-6a65271fa81a',
    ),
  );
  $terms[] = array(
    'name' => 'Science Philanthropy Alliance',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '303e9ab5-6bc2-4d69-9b58-5e0d7e56342e',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'City University Of New York',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '321d1837-cecc-43f6-9558-51646ebbd8c0',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'University Of Texas, Austin',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '34de25f0-f9bd-4b77-808e-eb500aed29a4',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Performing Arts',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '34eb86b3-f3fb-440c-9091-d4960a261ab4',
    'vocabulary_machine_name' => 'research_area',
    'field_term_icon' => array(),
    'field_term_image' => array(),
    'field_term_icon_with_color_' => array(),
    'parent' => array(
      0 => '080b773f-5832-47fb-92d9-6a65271fa81a',
    ),
  );
  $terms[] = array(
    'name' => 'University Of California Santa Cruz',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '35958178-5edb-41c4-97d4-d6c0b3cbd658',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'University Of Chicago',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '363e3112-2df2-4bfb-b908-9ab6437682ac',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Cybersecurity',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3729e5f2-6df3-4b7b-ba66-5202271f57c4',
    'vocabulary_machine_name' => 'research_area',
    'field_term_icon' => array(),
    'field_term_image' => array(),
    'field_term_icon_with_color_' => array(),
    'parent' => array(
      0 => '797fa9c6-81a9-4032-b846-763ed1162542',
    ),
  );
  $terms[] = array(
    'name' => 'Photonics / Imaging',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '386d47c3-6618-4259-b50e-74168edb92f9',
    'vocabulary_machine_name' => 'research_area',
    'field_term_icon' => array(),
    'field_term_image' => array(),
    'field_term_icon_with_color_' => array(),
    'parent' => array(
      0 => '797fa9c6-81a9-4032-b846-763ed1162542',
    ),
  );
  $terms[] = array(
    'name' => 'Diagnostics',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3885c07f-0a13-4820-afe6-ff73f88972b7',
    'vocabulary_machine_name' => 'research_area',
    'field_term_icon' => array(),
    'field_term_image' => array(),
    'field_term_icon_with_color_' => array(),
    'parent' => array(
      0 => '571713b2-f33e-448f-a4bc-fc967f7dbf1d',
    ),
  );
  $terms[] = array(
    'name' => 'Harvard College',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '395f623d-11c5-426f-a349-6b26b9826125',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Geology',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3b120fe0-3a46-437a-9d8c-120f97855a1c',
    'vocabulary_machine_name' => 'research_area',
    'field_term_icon' => array(),
    'field_term_image' => array(),
    'field_term_icon_with_color_' => array(),
    'parent' => array(
      0 => '0b1631a9-faa8-47a2-8de3-834fbc6960d2',
    ),
  );
  $terms[] = array(
    'name' => 'Computational Sciences / Mathematics',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3b1b23a1-5703-42d5-85f9-bdf8d975add8',
    'vocabulary_machine_name' => 'research_area',
    'field_term_icon' => array(),
    'field_term_image' => array(),
    'field_term_icon_with_color_' => array(),
    'parent' => array(
      0 => '797fa9c6-81a9-4032-b846-763ed1162542',
    ),
  );
  $terms[] = array(
    'name' => 'Indiana Univ-Purdue Univ At Indianapolis',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3c215489-4896-4ed4-b628-1b340275aec0',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'University Of Utah',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3c307ba7-fa71-4e7a-aaf7-468e4acf9d07',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'California Institute Of Technology',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3ce672e0-9b5e-4352-866d-6153729a0db3',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'University Of California At Davis',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3d2c53c9-8c31-49b5-a62f-473fa008369c',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Linguistics',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4066e723-5114-4c4f-b466-7c05ad5e09c0',
    'vocabulary_machine_name' => 'research_area',
    'field_term_icon' => array(),
    'field_term_image' => array(),
    'field_term_icon_with_color_' => array(),
    'parent' => array(
      0 => '080b773f-5832-47fb-92d9-6a65271fa81a',
    ),
  );
  $terms[] = array(
    'name' => 'Informational Sciences / Internet',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '423068e6-a8b9-4f9b-83b3-d8b4c2ad8004',
    'vocabulary_machine_name' => 'research_area',
    'field_term_icon' => array(),
    'field_term_image' => array(),
    'field_term_icon_with_color_' => array(),
    'parent' => array(
      0 => '797fa9c6-81a9-4032-b846-763ed1162542',
    ),
  );
  $terms[] = array(
    'name' => 'Rensselaer Polytechnic Institute',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '42780d93-5978-4991-9368-5fcf17cbc2b5',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Drexel University',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '42e5f6c3-681a-4d5a-8cea-9c89b9e80cfa',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'University Of Massachusetts Medical School - Worcester',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '43ce7a3b-548d-4732-837a-41f50dfb6fca',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Rice University',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4713ef4e-c12d-4e5c-a05d-53898f776a61',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Anthropology',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4959653f-bcbb-406b-b20f-7368bbcf4ba1',
    'vocabulary_machine_name' => 'research_area',
    'field_term_icon' => array(),
    'field_term_image' => array(),
    'field_term_icon_with_color_' => array(),
    'parent' => array(
      0 => '080b773f-5832-47fb-92d9-6a65271fa81a',
    ),
  );
  $terms[] = array(
    'name' => 'University Of Massachusetts Lowell',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4c26508b-0761-435a-b060-8bb3a33a89f0',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Scripps Translational Science Institute',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4edb57b7-21d7-4ef2-9191-2ef371083704',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Washington State University',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '507f960a-4d3b-4fcf-bfcf-e4b3aff5457d',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'University Of California Los Angeles',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '567c2835-87c2-4abe-8df4-dfabed9c5959',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Life',
    'description' => 'Marfa vinyl literally Helvetica roof party, food truck hella +1 Wes Anderson Blue Bottle. Mumblecore post-ironic crucifix try-hard. Kogi letterpress 3 wolf moon.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '571713b2-f33e-448f-a4bc-fc967f7dbf1d',
    'vocabulary_machine_name' => 'research_area',
    'field_term_icon' => array(),
    'field_term_image' => array(),
    'field_term_icon_with_color_' => array(),
  );
  $terms[] = array(
    'name' => 'University Of Virginia',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '59affc35-ecf3-4be1-b06d-dcbd3bb3dfe0',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Washington University',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '59b6984a-4c51-4199-bba6-b94b68022656',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'University Of California, San Francisco',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '5b7f3f6c-dcc4-46e4-87e1-3f7f86bed910',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'University Of Rochester',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '5bee574a-e129-43a2-8226-e84585a03c90',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Dartmouth College',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '5cbe9dcf-93fc-4bd0-85ea-906d1dc51b6d',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'University Of Georgia',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '5d754dff-d58f-499e-b107-91d5edb14cd9',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Claremont Mckenna College',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '5d9090e4-ea49-4170-b58e-def80a40b2e7',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Lawrence Livermore National Laboratory',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '5e00ac9b-7682-42a9-98f6-fbbb30dff1f3',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'University Of Pennsylvania',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '60004ec3-a8f9-488f-b722-aaf03f0dd9ad',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Arizona State University-Tempe Campus',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6040eed8-9f45-415e-bcc0-066974bf4e48',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'University Of California Berkeley',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '670b7851-bea4-4581-91d6-3ff4679acf4b',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'University Of Michigan',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6721441d-bd2b-4ac0-94c5-0d1b694eb2b8',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Icahn School Of Medicine At Mount Sinai',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '674d65cc-958e-41a2-bb7a-bfe7fe21adab',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Kent State University At Kent',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '68439a75-e3aa-4a4b-bd80-9fc574c13d9e',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Ohio University Athens',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6c18d222-17b6-44c5-8398-29df4a0f216a',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'University Of Houston',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6c87c410-e3e1-4e56-a7ea-dc08f3fa79be',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'University Of Oregon',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6d7143c4-20c4-4877-b4ab-e1eab554ecc3',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Oceanic',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6d9c721a-02b8-46be-8e74-25980d6739e6',
    'vocabulary_machine_name' => 'research_area',
    'field_term_icon' => array(),
    'field_term_image' => array(),
    'field_term_icon_with_color_' => array(),
    'parent' => array(
      0 => '0b1631a9-faa8-47a2-8de3-834fbc6960d2',
    ),
  );
  $terms[] = array(
    'name' => 'Kansas State University',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6f41eda1-7294-466c-8ce2-666b3432c55a',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Sociology',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6f65fb2f-b6b1-4674-af7f-46e70a7b15ef',
    'vocabulary_machine_name' => 'research_area',
    'field_term_icon' => array(),
    'field_term_image' => array(),
    'field_term_icon_with_color_' => array(),
    'parent' => array(
      0 => '080b773f-5832-47fb-92d9-6a65271fa81a',
    ),
  );
  $terms[] = array(
    'name' => 'Tufts University Boston',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '701da4ee-0149-4ab5-a96d-20c038ffb96e',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Semiconductor',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '70e99fb7-3ba6-4dc8-8749-edf35d364e09',
    'vocabulary_machine_name' => 'research_area',
    'field_term_icon' => array(),
    'field_term_image' => array(),
    'field_term_icon_with_color_' => array(),
    'parent' => array(
      0 => '797fa9c6-81a9-4032-b846-763ed1162542',
    ),
  );
  $terms[] = array(
    'name' => 'Robotics',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7556f57a-aadc-4db9-ba3c-1e721f030f1c',
    'vocabulary_machine_name' => 'research_area',
    'field_term_icon' => array(),
    'field_term_image' => array(),
    'field_term_icon_with_color_' => array(),
    'parent' => array(
      0 => '797fa9c6-81a9-4032-b846-763ed1162542',
    ),
  );
  $terms[] = array(
    'name' => 'Metabolic / Diabetes',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '77abddfb-fd88-4473-87c0-581dd1ef3c68',
    'vocabulary_machine_name' => 'research_area',
    'field_term_icon' => array(),
    'field_term_image' => array(),
    'field_term_icon_with_color_' => array(),
    'parent' => array(
      0 => '571713b2-f33e-448f-a4bc-fc967f7dbf1d',
    ),
  );
  $terms[] = array(
    'name' => 'Technology',
    'description' => 'Marfa vinyl literally Helvetica roof party, food truck hella +1 Wes Anderson Blue Bottle. Mumblecore post-ironic crucifix try-hard. Kogi letterpress 3 wolf moon. Marfa vinyl literally Helvetica roof party, food truck hella +1 Wes Anderson Blue Bottle. Mumblecore post-ironic crucifix try-hard. Kogi letterpress 3 wolf moon.',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '797fa9c6-81a9-4032-b846-763ed1162542',
    'vocabulary_machine_name' => 'research_area',
    'field_term_icon' => array(),
    'field_term_image' => array(),
    'field_term_icon_with_color_' => array(),
  );
  $terms[] = array(
    'name' => 'Aerospace',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '798186f2-1c7c-4273-964e-b3e4c9844584',
    'vocabulary_machine_name' => 'research_area',
    'field_term_icon' => array(),
    'field_term_image' => array(),
    'field_term_icon_with_color_' => array(),
    'parent' => array(
      0 => '797fa9c6-81a9-4032-b846-763ed1162542',
    ),
  );
  $terms[] = array(
    'name' => 'Florida International University',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7b2dbd67-a42d-4feb-a4f7-cdd39903e276',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Oregon State University',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7c68b36d-ad0e-476f-87f5-851e51ac0e9a',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Cold Spring Harbor Laboratory',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7f2eedb7-832c-4e4c-b4fa-7c8607715518',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Columbia University',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7f8d427b-9109-445d-91e6-b3e82b4ec69c',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'University Of Missouri-Columbia',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8017aedc-81c2-4542-af98-2fbc6c78006d',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Respiratory',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '802aea84-78d2-46d5-b07a-36c81cf0864b',
    'vocabulary_machine_name' => 'research_area',
    'field_term_icon' => array(),
    'field_term_image' => array(),
    'field_term_icon_with_color_' => array(),
    'parent' => array(
      0 => '571713b2-f33e-448f-a4bc-fc967f7dbf1d',
    ),
  );
  $terms[] = array(
    'name' => 'Music',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '80b366a6-31f8-4210-bad3-94a570007e45',
    'vocabulary_machine_name' => 'research_area',
    'field_term_icon' => array(),
    'field_term_image' => array(),
    'field_term_icon_with_color_' => array(),
    'parent' => array(
      0 => '080b773f-5832-47fb-92d9-6a65271fa81a',
    ),
  );
  $terms[] = array(
    'name' => 'Mount Desert Island Biological Laboratory',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '82921fa1-3062-4dba-877b-5a9e0e1ef078',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Baylor College Of Medicine',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '830aa313-7db2-48c1-95a8-8d329e9a4e4b',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'University Of Oklahoma Norman',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '838c4bf7-efdd-4726-9614-2b555d5090d4',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Lehigh University',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8465e0d1-6d7d-4db0-91dc-ba08680f819e',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Psychology',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '85a7752e-daaa-4c02-aa87-2c4ca3d795de',
    'vocabulary_machine_name' => 'research_area',
    'field_term_icon' => array(),
    'field_term_image' => array(),
    'field_term_icon_with_color_' => array(),
    'parent' => array(
      0 => '080b773f-5832-47fb-92d9-6a65271fa81a',
    ),
  );
  $terms[] = array(
    'name' => 'The Scripps Research Institute',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '899a4a54-9546-4769-905a-3ef1246cd98d',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'International Computer Science Institute',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8bfd6e2b-2086-4b7c-bcea-04bf19cd4147',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Telecommunications',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8c16c06b-504d-418f-b754-3c80bc48bd5d',
    'vocabulary_machine_name' => 'research_area',
    'field_term_icon' => array(),
    'field_term_image' => array(),
    'field_term_icon_with_color_' => array(),
    'parent' => array(
      0 => '797fa9c6-81a9-4032-b846-763ed1162542',
    ),
  );
  $terms[] = array(
    'name' => 'Chemical',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '90fabab4-60d8-42c3-baf2-088a56f6b518',
    'vocabulary_machine_name' => 'research_area',
    'field_term_icon' => array(),
    'field_term_image' => array(),
    'field_term_icon_with_color_' => array(),
    'parent' => array(
      0 => '0b1631a9-faa8-47a2-8de3-834fbc6960d2',
    ),
  );
  $terms[] = array(
    'name' => 'University Of California Santa Barbara',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '95fa8e78-d1c8-4446-82a3-fd6a07574888',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Temple Univ Of The Commonwealth',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '980560eb-bc06-45ac-a5f1-b7c6b6f72364',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'National Jewish Health',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '98604917-2688-4074-9a41-d5068e289e53',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Rutgers, The State Univ Of N.J.',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '99158ef5-0832-4663-a09f-22a9a41c4526',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'University Of Alabama At Birmingham',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '996b6920-79b0-4a2c-9f9c-eea98c544603',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Vanderbilt University',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '9bb5fb54-5d00-400d-98d9-93274ec3e6f2',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Electronics / Sensors',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a2b84603-2f7d-4634-8250-8c2db567e736',
    'vocabulary_machine_name' => 'research_area',
    'field_term_icon' => array(),
    'field_term_image' => array(),
    'field_term_icon_with_color_' => array(),
    'parent' => array(
      0 => '797fa9c6-81a9-4032-b846-763ed1162542',
    ),
  );
  $terms[] = array(
    'name' => 'University Of Florida',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a3b0ac5f-3abc-4c6c-b2d1-4fbb5d0233f9',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Syracuse University',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a444bbd2-79de-4492-89d5-28905e07e214',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'State University Of New York At Buffalo',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a4b9f91c-014d-4d47-9bf3-c02a913f496a',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Immunology / Inflammatory',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a58146f6-c07f-411b-a2b5-75f09a8b8984',
    'vocabulary_machine_name' => 'research_area',
    'field_term_icon' => array(),
    'field_term_image' => array(),
    'field_term_icon_with_color_' => array(),
    'parent' => array(
      0 => '571713b2-f33e-448f-a4bc-fc967f7dbf1d',
    ),
  );
  $terms[] = array(
    'name' => 'Indiana University Bloomington',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a5ae80de-6411-488f-908e-5a9d98630dc9',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Northwestern University At Chicago',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a639f954-aae6-4cc3-bb43-c6787374b9a2',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Univ Of North Carolina Chapel Hill',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a6417b1a-27fd-4544-9137-5d34df63a111',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Harvard University',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a962f6a1-4585-487f-a5c7-062e59df0cc2',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'University Of Vermont & St Agric College',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'aa53ee2e-21e6-4a77-9670-7475c81676e3',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'North-West University',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ac73fd82-fa40-42a7-a490-8f926e6e1f94',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Circulatory',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ac8fc89b-33b7-4e6c-bc77-85c303551d35',
    'vocabulary_machine_name' => 'research_area',
    'field_term_icon' => array(),
    'field_term_image' => array(),
    'field_term_icon_with_color_' => array(),
    'parent' => array(
      0 => '571713b2-f33e-448f-a4bc-fc967f7dbf1d',
    ),
  );
  $terms[] = array(
    'name' => 'Education',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ad63341f-18e9-4afd-9549-ae096b4681a8',
    'vocabulary_machine_name' => 'research_area',
    'field_term_icon' => array(),
    'field_term_image' => array(),
    'field_term_icon_with_color_' => array(),
    'parent' => array(
      0 => '080b773f-5832-47fb-92d9-6a65271fa81a',
    ),
  );
  $terms[] = array(
    'name' => 'University Of Puerto Rico Med Sciences',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ad850bce-82f8-42da-8eea-cc354a2a76c9',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'University Of Massachusetts Amherst',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'affaecea-f0ff-4251-9526-ce71ae588950',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'North Carolina State University Raleigh',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b2aaf639-bbca-4667-9b38-fd12f17e0d4a',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'University Of California San Diego',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b2b09024-ccfd-4e7a-96b2-2cc3b4c81021',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Neurological / Cognitive',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b475d643-98d5-419f-9aea-9849cc32f19e',
    'vocabulary_machine_name' => 'research_area',
    'field_term_icon' => array(),
    'field_term_image' => array(),
    'field_term_icon_with_color_' => array(),
    'parent' => array(
      0 => '571713b2-f33e-448f-a4bc-fc967f7dbf1d',
    ),
  );
  $terms[] = array(
    'name' => 'Genomics / Congenital',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b5b3f43f-7413-4efb-964f-7b4062f65df8',
    'vocabulary_machine_name' => 'research_area',
    'field_term_icon' => array(),
    'field_term_image' => array(),
    'field_term_icon_with_color_' => array(),
    'parent' => array(
      0 => '571713b2-f33e-448f-a4bc-fc967f7dbf1d',
    ),
  );
  $terms[] = array(
    'name' => 'Literary Arts',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'be31b546-38d2-4a2a-acbc-776ce40cf719',
    'vocabulary_machine_name' => 'research_area',
    'field_term_icon' => array(),
    'field_term_image' => array(),
    'field_term_icon_with_color_' => array(),
    'parent' => array(
      0 => '080b773f-5832-47fb-92d9-6a65271fa81a',
    ),
  );
  $terms[] = array(
    'name' => 'University Of Notre Dame',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c041892d-325b-4f4b-af9e-9eb4c685d0eb',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'University Corporation For Atmospheric Research',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c1b1ab24-8cc5-499b-ba82-89cf84958e49',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'University Of Maryland College Pk Campus',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c845aad3-576c-4186-9177-b84c4f8545f9',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Johns Hopkins University',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c883cfdc-33b2-4f72-850c-6c78734321ed',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Telemedicine',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c968db8b-907d-427b-b0be-4aba80ef35e3',
    'vocabulary_machine_name' => 'research_area',
    'field_term_icon' => array(),
    'field_term_image' => array(),
    'field_term_icon_with_color_' => array(),
    'parent' => array(
      0 => '571713b2-f33e-448f-a4bc-fc967f7dbf1d',
    ),
  );
  $terms[] = array(
    'name' => 'New York University',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ca07249b-b19d-4ff3-920e-48459bab43cf',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Proteomics',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ce222bba-6b64-45e8-965a-09147d4e21ff',
    'vocabulary_machine_name' => 'research_area',
    'field_term_icon' => array(),
    'field_term_image' => array(),
    'field_term_icon_with_color_' => array(),
    'parent' => array(
      0 => '571713b2-f33e-448f-a4bc-fc967f7dbf1d',
    ),
  );
  $terms[] = array(
    'name' => 'Northeastern University',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ce4afc9b-d5fd-4679-ace6-e3caff9e6ffc',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'University Of Southern California',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'cea3ea14-728e-4234-af08-f5a2dfeb91fe',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Chemistry',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd179c7fb-a7eb-4b9b-9e20-89e43c49aa86',
    'vocabulary_machine_name' => 'research_area',
    'field_term_icon' => array(),
    'field_term_image' => array(),
    'field_term_icon_with_color_' => array(),
    'parent' => array(
      0 => '797fa9c6-81a9-4032-b846-763ed1162542',
    ),
  );
  $terms[] = array(
    'name' => 'Carnegie-Mellon University',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd1d3eb12-632c-483f-a76d-d1e023beb67a',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Stanford Research Institute',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd23f4b85-e32a-4aac-84ce-7d5b7c2c34e6',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Mayo Medical School',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd3b6d1cf-7458-4eaf-912b-56233372d7ec',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Virginia Polytechnic Inst And St Univ',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd430ed84-5c36-45b9-a9a2-33a94035f736',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Stanford University',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd602db2a-d539-4aa0-b859-5cd30af5cfb3',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Emory University',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd70379fb-12db-4407-a332-3938c2d3ec91',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'University Of Arizona',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd71b4f5a-fc6b-44da-a04e-31397cc78849',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Virtual Arts',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd9821a20-fb73-4d17-9fcc-0b28d2f1795a',
    'vocabulary_machine_name' => 'research_area',
    'field_term_icon' => array(),
    'field_term_image' => array(),
    'field_term_icon_with_color_' => array(),
    'parent' => array(
      0 => '080b773f-5832-47fb-92d9-6a65271fa81a',
    ),
  );
  $terms[] = array(
    'name' => 'Florida State University',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'da2f8dbc-1933-49c1-aff1-b9b09e3506f8',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'University Of Colorado Boulder',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'dbafbb54-ed1d-4863-b2dd-c033d9922bbf',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Illinois Institute Of Technology',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e0db649c-51b7-4e7e-bef5-fd596e7a3959',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Colorado School Of Mines',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e43e32c8-80ff-48cd-b413-886aaabbe3d3',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Toyota Technological Institute',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e5237b78-d607-4eae-a2ed-f95faaae91ee',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Lawrence Berkeley National Laboratory',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e5bc2a57-340a-4749-b9b5-7f64b02918fd',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'University Of Pittsburgh',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e6c4b378-73b0-4b27-b328-0d7d3f5a8626',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Archaeology',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e6f3f673-29b3-4e8a-b20e-684c39234826',
    'vocabulary_machine_name' => 'research_area',
    'field_term_icon' => array(),
    'field_term_image' => array(),
    'field_term_icon_with_color_' => array(),
    'parent' => array(
      0 => '080b773f-5832-47fb-92d9-6a65271fa81a',
    ),
  );
  $terms[] = array(
    'name' => 'Oncology / Cancer',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e7490983-c679-404b-a28e-99075a1fd37f',
    'vocabulary_machine_name' => 'research_area',
    'field_term_icon' => array(),
    'field_term_image' => array(),
    'field_term_icon_with_color_' => array(),
    'parent' => array(
      0 => '571713b2-f33e-448f-a4bc-fc967f7dbf1d',
    ),
  );
  $terms[] = array(
    'name' => 'Ohio State University',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e801b52c-8d58-4689-9902-535cc15a3765',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Fluidics',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e9230a73-9c10-4190-90f3-2e85cdb70ff7',
    'vocabulary_machine_name' => 'research_area',
    'field_term_icon' => array(),
    'field_term_image' => array(),
    'field_term_icon_with_color_' => array(),
    'parent' => array(
      0 => '797fa9c6-81a9-4032-b846-763ed1162542',
    ),
  );
  $terms[] = array(
    'name' => 'Ecology',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e9a031ec-28cd-4a41-8831-02263dd8681b',
    'vocabulary_machine_name' => 'research_area',
    'field_term_icon' => array(),
    'field_term_image' => array(),
    'field_term_icon_with_color_' => array(),
    'parent' => array(
      0 => '0b1631a9-faa8-47a2-8de3-834fbc6960d2',
    ),
  );
  $terms[] = array(
    'name' => 'Cornell University',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ebcf8bbb-fea9-4252-b41a-803624b8a33b',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Materials Science / Physics',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ef33ee2f-2587-4967-ad25-8f432180d82c',
    'vocabulary_machine_name' => 'research_area',
    'field_term_icon' => array(),
    'field_term_image' => array(),
    'field_term_icon_with_color_' => array(),
    'parent' => array(
      0 => '797fa9c6-81a9-4032-b846-763ed1162542',
    ),
  );
  $terms[] = array(
    'name' => 'University Of Alaska Fairbanks',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f1415454-f3e0-453b-9f44-def50155185f',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Texas A&M University',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f295a2de-4b58-4c52-b055-e40aa0da5235',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Princeton University',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f465d791-0938-450e-96ea-fb5b468cec2f',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'University Of Minnesota',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f702adcf-1df6-4e91-93ad-4f605e598656',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Boston University (Charles River Campus)',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f73f05c1-bd92-422e-999c-226814363910',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Georgia Institute Of Technology',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f78a6945-2195-4b58-b6d3-81f5990c3c2d',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Law / Ethics',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f8abb3fa-fc60-40fb-877f-234caa93b6b6',
    'vocabulary_machine_name' => 'research_area',
    'field_term_icon' => array(),
    'field_term_image' => array(),
    'field_term_icon_with_color_' => array(),
    'parent' => array(
      0 => '080b773f-5832-47fb-92d9-6a65271fa81a',
    ),
  );
  $terms[] = array(
    'name' => 'Pennsylvania State University',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f9274932-307c-4445-80fd-3880b53bee42',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'University Of South Florida',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f97c6b8e-750c-4dd3-9ed1-313bc791d0f2',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Atmospheric / Space',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'fa3189d0-a512-437e-a0c0-b157bda7dfea',
    'vocabulary_machine_name' => 'research_area',
    'field_term_icon' => array(),
    'field_term_image' => array(),
    'field_term_icon_with_color_' => array(),
    'parent' => array(
      0 => '0b1631a9-faa8-47a2-8de3-834fbc6960d2',
    ),
  );
  $terms[] = array(
    'name' => 'Oregon Health & Science University',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'fa728882-33dd-410f-a1c6-4f53aab7ca21',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Remediation',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'fafacbbf-ba8f-40f6-8fb7-789f20c7ed02',
    'vocabulary_machine_name' => 'research_area',
    'field_term_icon' => array(),
    'field_term_image' => array(),
    'field_term_icon_with_color_' => array(),
    'parent' => array(
      0 => '0b1631a9-faa8-47a2-8de3-834fbc6960d2',
    ),
  );
  $terms[] = array(
    'name' => 'Political Science',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'fc3fe7f2-0656-42ce-a6ae-451c064ff86d',
    'vocabulary_machine_name' => 'research_area',
    'field_term_icon' => array(),
    'field_term_image' => array(),
    'field_term_icon_with_color_' => array(),
    'parent' => array(
      0 => '080b773f-5832-47fb-92d9-6a65271fa81a',
    ),
  );
  $terms[] = array(
    'name' => 'Massachusetts Institute Of Technology',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ffa2ed5b-f5a0-4d0c-8f8e-8855f9dab951',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'Brown University',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ffb33886-c09b-4a72-afb0-07ce610b01ce',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  $terms[] = array(
    'name' => 'University Of Washington',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ffd4c349-9960-4e44-b395-f8e2f5c6e2ce',
    'vocabulary_machine_name' => 'university_or_institution',
    'field_logo' => array(),
  );
  return $terms;
}
