<?php
/**
 * @file
 * Code for the BF FA Dashboard feature.
 */

include_once 'bf_fa_dashboard.features.inc';

/**
 * Implements hook_block_info().
 */
function bf_fa_dashboard_block_info() {
  $blocks['fa_menu'] = array(
    'info' => 'Financial Advisor Menu',
    'cache' => DRUPAL_CACHE_PER_ROLE,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function bf_fa_dashboard_block_view($delta = '') {
  global $user;

  if ($delta == 'fa_menu') {
    $block['subject'] = '';
    $block['content'] = array(
      array('#markup' => '<div><a class="btn btn-black" href="/user">Dashboard</a><a class="btn btn-black" href="#">Help Desk</a><a class="btn btn-purple" href="/node/add/giving-proposal">+ Create a Proposal</a></div>'),
    );

    if (!empty($user->picture)) {
      $block['content'][] = array('#markup' => '<div class="user-picture">' . theme('image_style', array(
          'style_name' => 'thumbnail',
          'path' => $user->picture,
        )) . '</div>');
    }

    $block['content'][] = array('#markup' => '<div>' . l('Edit Profile', 'user/' . $user->uid . '/edit', array(
        'attributes' => array('class' => array('btn', 'btn-black')),
      )) . '</div>');
  }
  return $block;
}
